# 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
---
- name: remove the test database
  action: mysql_db name=test state=absent
  tags: config

- name: create mysql databases
  action: mysql_db name={{item.database}} state=present
  with_items: mysql
  tags: config

- name: create mysql users
  mysql_user: name={{item.user}} priv={{item.database}}.*:ALL state=present password={{item.password}} append_privs=yes
  tags: config
  with_items: mysql

